Repository nodejs/undici, pull requests merged in 2020-08, with the labels that each got.

#345 fix: close() deadlock
  README.md
  benchmarks/index.js
  lib/client-connect.js
  lib/client-pipeline.js
  lib/client-request.js
  lib/client-stream.js
  lib/client-upgrade.js
  lib/client.js
  lib/request.js
  test/client-dispatch.js
  test/pool.js
  test/request-timeout.js
Labels: bug, semver-major

#358 Reuse TLS sessions
  lib/core/client.js
  lib/core/symbols.js
  test/client-errors.js
  test/fixtures/ca.pem
  test/fixtures/cert.pem
  test/fixtures/key.pem
  test/tls-session-reuse.js
Labels: enhancement

#366 refactor: simplify busy
  README.md
  lib/core/client.js
  lib/core/request.js
  test/client-pipelining.js
  test/pipeline-pipelining.js
Labels: semver-major
