Repository nodejs/undici, pull requests merged in 2021-04, with the labels that each got.

#653 fix: refresh timer on parser resume
  lib/client.js
  test/client-timeout.js
Labels: Client

#646 fix: don't headersTimeout while writing request body
  lib/client.js
  test/client-timeout.js
Labels: semver-major

#665 fix: emit disconnect after destroy()
  lib/client.js
  test/client-connect.js
  test/client-pipeline.js
  test/client-pipelining.js
  test/client-stream.js
  test/client-write-max-listeners.js
  test/client.js
  test/content-length.js
  test/get-head-body.js
  test/pipeline-pipelining.js
  test/tls.js
Labels: semver-major

#626 Added WG Charter
  GOVERNANCE.md
  README.md
Labels: tsc-agenda

#763 feat: connect
  lib/client.js
  lib/core/connect.js
  lib/core/request.js
  lib/core/symbols.js
  lib/core/util.js
  lib/pool.js
  test/client-errors.js
  test/tls-session-reuse.js
Labels: Status: help-wanted
